version: 2.1

orbs:
  windows: circleci/windows@2.2.0

jobs:
  build:
    description: Setup and run application tests
    executor:
      name: windows/default
    steps:
      - checkout
      - run: choco install gitversion.portable
      #- run: choco install netfx-4.8-devpack
      - run: choco install netfx-4.7.2-devpack
      - run: dotnet --list-sdks
      - run: reg query "HKLM\SOFTWARE\Microsoft\Net Framework Setup\NDP" /s  
      # - run: choco install uninstalltool
      - run: choco uninstall dotnetcore-sdk
      - run: choco uninstall dotnet-5.0.411-sdk
      - run: choco uninstall dotnet-5.0.401-sdk
      - run: get-host|Select-Object 
      # - run: dotnet-core-uninstall list --sdk
      - run: dotnet --list-sdks
      - run: choco install dotnetcore-sdk --version=3.1.426
      - run: dotnet --list-sdks
      #- run:  dotnet restore .\all_projects.sln -p:TargetFramework=net471
workflows:
  build:
    jobs:
      - build